
--14)FIX
DROP PROC IF EXISTS EX_14_READ_UONG_UNCOMMITTED_READ_FIX 
go

CREATE PROC EX_14_READ_UONG_UNCOMMITTED_READ_FIX
AS
BEGIN
    BEGIN TRAN 
        BEGIN TRY 
            SELECT * FROM DOUONG
            WAITFOR DELAY '00:00:05'
            SELECT * FROM DOUONG

        END TRY 

        BEGIN CATCH 
            ROLLBACK 
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_14_INSERT_UONG_FIX
GO
CREATE PROC EX_14_INSERT_UONG
        @MATD_DU CHAR(50),
        @MADU CHAR(6),
        @TENDU nvarchar(50),
        @MIEUTA nvarchar(300),
        @GIA FLOAT
AS
BEGIN
    BEGIN TRAN
        IF  EXISTS(SELECT * FROM DOUONG WHERE MADU = @MADU AND MATD_DU = @MATD_DU)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
    INSERT INTO  DOUONG WITH (UPDLOCK)(MATD_DU, MADU, TENDU, MIEUTA, GIA) 
    VALUES (@MATD_DU, @MADU, @TENDU, @MIEUTA, @GIA)        
    SELECT *  FROM DOUONG
    WAITFOR DELAY '00:00:05'
    COMMIT TRAN 
    RETURN 1
END 

GO

GO
DROP PROC IF EXISTS EX_14_UPDATE_UONG_FIX
GO
CREATE PROC EX_14_UPDATE_UONG_FIX
        @MATD_DU CHAR(50),
        @MADU CHAR(6),
        @TENDU nvarchar(50),
        @MIEUTA nvarchar(300),
        @GIA FLOAT
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
    BEGIN TRAN
          IF NOT EXISTS(SELECT * FROM DOUONG WHERE MADU = @MADU AND MATD_DU = @MATD_DU)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
  
    SELECT *  FROM DOUONG 
    WAITFOR DELAY '00:00:05'
    UPDATE DOUONG 
    SET TENDU = @TENDU WHERE MADU = @MADU
    COMMIT TRAN 
    RETURN 1
END 
