
--23) FIX

DROP PROC IF EXISTS EX_23_READ_SOLUONG_LOST_UPDATE_FIX
go

CREATE PROC EX_23_READ_SOLUONG_LOST_UPDATE_FIX
AS
BEGIN
    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM  THUCDON_DA 

                WAITFOR DELAY '00:00:15'

                SELECT * FROM  THUCDON_DA 
        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 
GO
DROP PROC IF EXISTS EX_23_UPDATE_SOLUONGA_LOST_UPDATE_FIX 
GO
CREATE PROC EX_23_UPDATE_SOLUONGA_LOST_UPDATE_FIX 
   @MATD_DA      char(6),
   @MADT       char(6),
   @SOLUONGMON  FLOAT
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
    BEGIN TRAN
    BEGIN TRY
    IF EXISTS (SELECT * FROM THUCDON_DA WHERE SOLUONGMON < @SOLUONGMON)
        BEGIN
                PRINT N'LỖI'

            ROLLBACK TRAN
            RETURN 1
        END
        IF NOT EXISTS (SELECT * FROM THUCDON_DA WHERE MATD_DA = @MATD_DA AND MADT = @MADT)
        BEGIN
            ROLLBACK TRAN
            RETURN 1
        END

        SELECT * FROM THUCDON_DA   
        WAITFOR DELAY '00:00:10'
        UPDATE THUCDON_DA SET SOLUONGMON = @SOLUONGMON - 1 WHERE MATD_DA = @MATD_DA AND MADT = @MADT
        SELECT * FROM THUCDON_DA 
    END TRY

    BEGIN CATCH
        ROLLBACK TRAN 
        RETURN 0
    END CATCH

    COMMIT TRAN
    RETURN 1
END


GO
DROP PROC IF EXISTS EX_23_UPDATE_SOLUONGB_LOST_UPDATE_FIX  
GO
CREATE PROC EX_23_UPDATE_SOLUONGB_LOST_UPDATE_FIX 
   @MATD_DA      char(6),
   @MADT       char(6),
   @SOLUONGMON  FLOAT
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
    BEGIN TRAN
    BEGIN TRY
    IF EXISTS (SELECT * FROM THUCDON_DA WHERE SOLUONGMON < @SOLUONGMON)
        BEGIN
                PRINT N'LỖI'

            ROLLBACK TRAN
            RETURN 1
        END
        IF NOT EXISTS (SELECT * FROM THUCDON_DA WHERE MATD_DA = @MATD_DA AND MADT = @MADT)
        BEGIN
            ROLLBACK TRAN
            RETURN 1
        END
        SELECT * FROM THUCDON_DA   
        UPDATE THUCDON_DA SET SOLUONGMON = @SOLUONGMON - 2 WHERE MATD_DA = @MATD_DA AND MADT = @MADT
        SELECT * FROM THUCDON_DA 
    END TRY

    BEGIN CATCH
        ROLLBACK TRAN 
        RETURN 0
    END CATCH

    COMMIT TRAN
    RETURN 1
END