--3 FIX
DROP PROC IF EXISTS EX_3_READ_DH_UNCOMMITTED_READ_FIX 
go

CREATE PROC EX_3_READ_DH_UNCOMMITTED_READ_FIX 
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ COMMITTED 
    BEGIN TRAN 
        BEGIN TRY 
            SELECT * FROM DONHANG
           

        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_3_UPDATE_DH_UNCOMMITTED_READ_FIX 
GO
CREATE PROC EX_3_UPDATE_DH_UNCOMMITTED_READ_FIX 
        @MADH CHAR(50),
        @MAKH CHAR(6),
        @MACN CHAR(6),
        @GHICHU nvarchar(100) 
AS
BEGIN
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM DONHANG WHERE MADH = @MADH AND MAKH = @MAKH)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
        UPDATE DONHANG SET GHICHU = @GHICHU WHERE MADH = @MADH AND MAKH = @MAKH
        SELECT *  FROM DONHANG
        WAITFOR DELAY '00:00:05'  
    ROLLBACK TRAN 
    RETURN 1
END