--5) FIX
DROP PROC IF EXISTS EX_5_READ_MENU_UNREPEATABLE_READ_FIX 
GO
CREATE PROC EX_5_READ_MENU_UNREPEATABLE_READ_FIX
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
    BEGIN TRAN 
    BEGIN TRY 
            SELECT * FROM MONAN

            WAITFOR DELAY '00:00:05'

            SELECT * FROM MONAN
    END TRY 

    BEGIN CATCH 
        ROLLBACK TRAN
        RETURN 0
    END CATCH
    COMMIT TRAN
    RETURN 1
END 

GO


DROP PROC IF EXISTS EX_5_UPDATE_MONAN_UNREPEATABLE_READ_FIX  
GO 
CREATE PROC EX_5_UPDATE_MONAN_UNREPEATABLE_READ_FIX
        @TENMON NVARCHAR(50),
        @MAMA CHAR(6),
        @MATD_MA CHAR(6)
AS
BEGIN
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM MONAN WHERE MAMA = @MAMA AND MATD_DA = @MATD_MA)
        BEGIN
            ROLLBACK TRAN 
            RETURN 0
        END
        UPDATE MONAN SET TENMA = @TENMON WHERE MAMA = @MAMA AND MATD_DA = @MATD_MA
    COMMIT TRAN 
    RETURN 1

END

