--6) FIX
DROP PROC IF EXISTS EX_6_READ_MONAN_UNREPEATABLE_READ_FIX 
go

CREATE PROC EX_6_READ_MONAN_UNREPEATABLE_READ_FIX
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM MONAN

                WAITFOR DELAY '00:00:05'

                SELECT * FROM MONAN
        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_6_UPDATE_MONAN_UNREPEATABLE_READ_FIX  
GO
CREATE PROC EX_6_UPDATE_MONAN_UNREPEATABLE_READ_FIX
        @MAMA CHAR(6),
        @MATD_MA CHAR(6),
        @GIA FLOAT
AS
BEGIN
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM MONAN WHERE MAMA = @MAMA AND MATD_DA = @MATD_MA)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
        UPDATE MONAN SET GIA = @GIA WHERE MAMA = @MAMA AND MATD_DA = @MATD_MA
    COMMIT TRAN 
    RETURN 1
END