
--15)FIX
DROP PROC IF EXISTS EX_15_READ_MONAN_FIX
go

CREATE PROC EX_15_READ_MONAN_FIX
AS
BEGIN
    BEGIN TRAN 
        BEGIN TRY 
            SELECT * FROM MONAN
            WAITFOR DELAY '00:00:05'
            SELECT * FROM MONAN

        END TRY 

        BEGIN CATCH 
            ROLLBACK 
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_15_INSERT_MONAN_FIX
GO
CREATE PROC EX_15_INSERT_MONAN_FIX
        @MATD_DA CHAR(50),
        @MAMA CHAR(6),
        @TENMA nvarchar(50),
        @MIEUTA nvarchar(300),
        @GIA FLOAT
AS
BEGIN
    BEGIN TRAN
        IF  EXISTS(SELECT * FROM MONAN WHERE MAMA = @MAMA AND MATD_DA = @MATD_DA)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
    INSERT INTO MONAN WITH (UPDLOCK) (MATD_DA, MAMA, TENMA, MIEUTA, GIA) 
    VALUES (@MATD_DA, @MAMA, @TENMA, @MIEUTA, @GIA)        
    SELECT *  FROM MONAN
    WAITFOR DELAY '00:00:05'
    COMMIT TRAN 
    RETURN 1
END 

GO

GO
DROP PROC IF EXISTS EX_15_UPDATE_MONAN_FIX
GO
CREATE PROC EX_15_UPDATE_MONAN_FIX
        @MATD_DA CHAR(50),
        @MAMA CHAR(6),
        @TENMA nvarchar(50),
        @MIEUTA nvarchar(300),
        @GIA FLOAT
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL  READ COMMITTED
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM MONAN WHERE MAMA = @MAMA AND MATD_DA = @MATD_DA)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
  
    SELECT *  FROM MONAN 
    WAITFOR DELAY '00:00:05'
    UPDATE MONAN 
    SET GIA = @GIA WHERE MAMA = @MAMA
    COMMIT TRAN 
    RETURN 1
END 
