
--17 LỖI
DROP PROC IF EXISTS EX_17_READ_MONAN_DEADLOCK
go

CREATE PROC EX_17_READ_MONAN_DEADLOCK
AS
BEGIN
    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM  MONAN 

                WAITFOR DELAY '00:00:13'

                SELECT * FROM  MONAN 
        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 

GO
DROP PROC IF EXISTS EX_17_UPDATE_TDB_DEADLOCK 
GO
CREATE PROC EX_17_UPDATE_TDB_DEADLOCK 
    @MATD_DA_1    char(6),
    @MAMA_1       char(6),
    @TENMA         nvarchar(30) ,
    @MATD_DA_2    char(6),
    @MAMA_2        char(6),
    @TENMA2       nvarchar(30) 
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL  READ UNCOMMITTED
    BEGIN TRAN
    BEGIN TRY

        IF NOT EXISTS (SELECT * FROM MONAN WHERE MATD_DA = @MATD_DA_1 AND MAMA = @MAMA_1 )
        BEGIN
            ROLLBACK TRAN
            RETURN 1
        END

        IF NOT EXISTS (SELECT * FROM MONAN WHERE MATD_DA = @MATD_DA_2 AND MAMA = @MAMA_2 )
        BEGIN
            ROLLBACK TRAN
            RETURN 1
        END

        SELECT * FROM MONAN  
        UPDATE MONAN SET TENMA = @TENMA WHERE MATD_DA = @MATD_DA_1 AND MAMA = @MAMA_1
        WAITFOR DELAY '00:00:05'
        UPDATE MONAN SET TENMA = @TENMA2 WHERE MATD_DA = @MATD_DA_2 AND MAMA = @MAMA_2
        SELECT * FROM MONAN  
    END TRY

    BEGIN CATCH
        ROLLBACK TRAN 
        RETURN 0
    END CATCH

    COMMIT TRAN
    RETURN 1
END
