

--19 LỖI
DROP PROC IF EXISTS EX_19_READ_MONAN_DEADLOCK
go

CREATE PROC EX_19_READ_MONAN_DEADLOCK
AS
BEGIN

    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM  THUCDON_DU 

                WAITFOR DELAY '00:00:13'

                SELECT * FROM  THUCDON_DU 
        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 

GO
DROP PROC IF EXISTS EX_19_UPDATE_TDB_DEADLOCK 
GO
CREATE PROC EX_19_UPDATE_TDB_DEADLOCK 
    @MATD_DU_1    char(6),
    @MADT_1       char(6),
    @TENTDDU_1      nvarchar(50) ,
    @MATD_DU_2    char(6),
    @MADT_2       char(6),
    @TENTDDU_2       nvarchar(50)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL  READ UNCOMMITTED
    BEGIN TRAN
    BEGIN TRY

        IF NOT EXISTS (SELECT * FROM THUCDON_DU WHERE MATD_DU = @MATD_DU_1 AND MADT = @MADT_1 )
        BEGIN
                PRINT 'A'

            ROLLBACK TRAN
            RETURN 1
        END

          IF NOT EXISTS (SELECT * FROM THUCDON_DU WHERE MATD_DU = @MATD_DU_2 AND MADT = @MADT_2 )
        BEGIN
        PRINT 'B'
            ROLLBACK TRAN
            RETURN 1
        END

        SELECT * FROM THUCDON_DU  
        UPDATE THUCDON_DU SET TENTDDU = @TENTDDU_1 WHERE MATD_DU = @MATD_DU_1 AND MADT = @MADT_1
        WAITFOR DELAY '00:00:05'
        UPDATE THUCDON_DU SET TENTDDU = @TENTDDU_2 WHERE MATD_DU = @MATD_DU_2 AND MADT = @MADT_2
        SELECT * FROM THUCDON_DU  
    END TRY

    BEGIN CATCH
        ROLLBACK TRAN 
        RETURN 0
    END CATCH

    COMMIT TRAN
    RETURN 1
END
