--4 LOI
DROP PROC IF EXISTS EX_4_READ_MONAN_UNCOMMITTED_READ 
go

CREATE PROC EX_4_READ_MONAN_UNCOMMITTED_READ
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    BEGIN TRAN 
        BEGIN TRY 
            SELECT * FROM MONAN

        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_4_INSERT_MONAN_UNCOMMITTED_READ
GO
CREATE PROC EX_4_INSERT_MONAN_UNCOMMITTED_READ
        @MATD_DA CHAR(50),
        @MAMA CHAR(6),
        @TENMA nvarchar(50),
        @MIEUTA nvarchar(300),
        @GIA FLOAT
AS
BEGIN
    BEGIN TRAN
        IF  EXISTS(SELECT * FROM MONAN WHERE MAMA = @MAMA AND MATD_DA =@MATD_DA)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
    INSERT INTO MONAN (MATD_DA, MAMA, TENMA, MIEUTA, GIA) 
    VALUES (@MATD_DA, @MAMA, @TENMA, @MIEUTA, @GIA)        
    SELECT *  FROM MONAN
    WAITFOR DELAY '00:00:05'
    ROLLBACK TRAN 
    RETURN 1
END 

GO