

--8) LOI

DROP PROC IF EXISTS EX_8_READ_DOUONG_UNREPEATABLE_READ 
go

CREATE PROC EX_8_READ_DOUONG_UNREPEATABLE_READ
AS
BEGIN
    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM DOUONG


        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_8_UPDATE_DOUONG_UNREPEATABLE_READ  
GO
CREATE PROC EX_8_UPDATE_DOUONG_UNREPEATABLE_READ  
        @MATD_DU CHAR(6),
        @MA_DU NVARCHAR(50),
        @GIA FLOAT
AS
BEGIN
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM DOUONG WHERE MATD_DU = @MATD_DU AND MADU = @MA_DU)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
        UPDATE DOUONG SET GIA = @GIA WHERE MATD_DU = @MATD_DU AND MADU = @MA_DU
                    WAITFOR DELAY '00:00:05'

    COMMIT TRAN 
    RETURN 1
END