--7 ) FIX 

DROP PROC IF EXISTS EX_7_READ_NHANVIEN_UNREPEATABLE_READ_FIX 
go

CREATE PROC EX_7_READ_NHANVIEN_UNREPEATABLE_READ_FIX
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM NHANVIEN

                WAITFOR DELAY '00:00:05'

                SELECT * FROM NHANVIEN
        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_7_UPDATE_NHANVIEN_UNREPEATABLE_READ_FIX  
GO
CREATE PROC EX_7_UPDATE_NHANVIEN_UNREPEATABLE_READ_FIX
        @MANV CHAR(6),
        @TENNV NVARCHAR(50)
AS
BEGIN
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
        UPDATE NHANVIEN SET TENNV = @TENNV WHERE MANV = @MANV
    COMMIT TRAN 
    RETURN 1
END
