--1) LOI
DROP PROC IF EXISTS EX_1_READ_INFO_UNCOMMITTED_READ  
GO
CREATE PROC EX_1_READ_INFO_UNCOMMITTED_READ
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    BEGIN TRAN 
    BEGIN TRY 
        SELECT * FROM MONAN 

    END TRY 

    BEGIN CATCH 
        ROLLBACK TRAN
        RETURN 0
    END CATCH
    COMMIT TRAN
    RETURN 1
END 
GO

DROP PROC IF EXISTS  EX_1_UPDATE_INFO_UNCOMMITTED_READ
GO 
CREATE PROC EX_1_UPDATE_INFO_UNCOMMITTED_READ
        @MAMA CHAR(6),
        @MATD_MA CHAR(6),
        @GIA FLOAT
AS
BEGIN
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM MONAN WHERE MAMA = @MAMA AND MATD_DA = @MATD_MA)
        BEGIN
            ROLLBACK TRAN 
            RETURN 0
        END
        UPDATE MONAN SET GIA = @GIA WHERE MAMA = @MAMA AND MATD_DA = @MATD_MA
        SELECT *  FROM MONAN  
        WAITFOR DELAY '00:00:05'  
		
		IF (@GIA < 0)
			BEGIN
				ROLLBACK TRAN
				RETURN 0
			END
    COMMIT TRAN
    RETURN 1
END
