
--23) LOI
DROP PROC IF EXISTS EX_23_READ_DONDK_LOST_UPDATE
go

CREATE PROC EX_23_READ_DONDK_LOST_UPDATE
AS
BEGIN
    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM  DON_DK 

                WAITFOR DELAY '00:00:15'

                SELECT * FROM  DON_DK 
        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 
GO
DROP PROC IF EXISTS EX_23_UPDATE_DONDKA_LOST_UPDATE 
GO
CREATE PROC EX_23_UPDATE_DONDKA_LOST_UPDATE 
   @MADDK      char(6),
   @MANV       char(6)
AS
BEGIN
    BEGIN TRAN
    BEGIN TRY
        IF NOT EXISTS (SELECT * FROM NHANVIEN WHERE MANV = @MANV)
        BEGIN
            ROLLBACK TRAN
            RETURN 1
        END


        IF NOT EXISTS (SELECT * FROM DON_DK WHERE MADDK = @MADDK AND MANV IS NULL)
        BEGIN
            ROLLBACK TRAN
            RETURN 1
        END

        SELECT * FROM DON_DK  WHERE MADDK = @MADDK 
        WAITFOR DELAY '00:00:10'
        UPDATE DON_DK SET MANV = @MANV WHERE MADDK = @MADDK 
        SELECT * FROM DON_DK WHERE MADDK = @MADDK 
    END TRY

    BEGIN CATCH
        ROLLBACK TRAN 
        RETURN 0
    END CATCH

    COMMIT TRAN
    RETURN 1
END


GO
DROP PROC IF EXISTS EX_23_UPDATE_DONDKB_LOST_UPDATE  
GO
CREATE PROC EX_23_UPDATE_DONDKB_LOST_UPDATE 
    @MADDK      char(6),
   @MANV       char(6)
AS
BEGIN
    BEGIN TRAN
    BEGIN TRY
        IF NOT EXISTS (SELECT * FROM NHANVIEN WHERE MANV = @MANV)
        BEGIN
            ROLLBACK TRAN
            RETURN 1
        END


        IF NOT EXISTS (SELECT * FROM DON_DK WHERE MADDK = @MADDK AND MANV IS NULL)
        BEGIN
            ROLLBACK TRAN
            RETURN 1
        END

        SELECT * FROM DON_DK WHERE MADDK = @MADDK

        UPDATE DON_DK SET  MANV = @MANV WHERE  MADDK = @MADDK
        SELECT * FROM DON_DK WHERE MADDK = @MADDK
    END TRY

    BEGIN CATCH
        ROLLBACK TRAN 
        RETURN 0
    END CATCH

    COMMIT TRAN
    RETURN 1
END
