
--5) LOI
DROP PROC IF EXISTS EX_5_READ_MENU_UNREPEATABLE_READ 
go

CREATE PROC EX_5_READ_MENU_UNREPEATABLE_READ
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM MONAN

                WAITFOR DELAY '00:00:05'

                SELECT * FROM MONAN
        END TRY 

        BEGIN CATCH 
            ROLLBACK 
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_5_UPDATE_MONAN_UNREPEATABLE_READ  
GO
CREATE PROC EX_5_UPDATE_MONAN_UNREPEATABLE_READ
        @TENMONAN NVARCHAR(50),
        @MAMA CHAR(6),
        @MATD_MA CHAR(6)
AS
BEGIN
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM MONAN WHERE MAMA = @MAMA AND MATD_DA = @MATD_MA)
        BEGIN
            ROLLBACK  
            RETURN 0
        END
        UPDATE MONAN SET TENMA = @TENMONAN WHERE MAMA = @MAMA AND MATD_DA = @MATD_MA
    COMMIT TRAN 
    RETURN 1
END
