
--9) LOI
DROP PROC IF EXISTS EX_9_READ_MONAN_PHANTOM
go

CREATE PROC EX_9_READ_MONAN_PHANTOM
AS
BEGIN
    BEGIN TRAN 
        BEGIN TRY 
                SELECT * FROM MONAN
                WAITFOR DELAY '00:00:15'
                SELECT * FROM MONAN
        END TRY 

        BEGIN CATCH 
            ROLLBACK TRAN
            RETURN 0
        END CATCH
    COMMIT TRAN
    RETURN 1
END 


GO
DROP PROC IF EXISTS EX_9_INSERT_MONAN_PHANTOM 
GO
CREATE PROC EX_9_INSERT_MONAN_PHANTOM 
        @MATD_DA CHAR(50),
        @MAMA CHAR(6),
        @TENMA nvarchar(50),
        @MIEUTA nvarchar(300),
        @GIA FLOAT
AS
BEGIN
    BEGIN TRAN
    BEGIN TRY 
            IF EXISTS(SELECT * FROM MONAN WHERE MAMA = @MAMA AND MATD_DA = @MATD_DA)
        BEGIN
            ROLLBACK TRAN 
            RETURN 0
        END
        INSERT INTO MONAN (MATD_DA, MAMA, TENMA, MIEUTA, GIA) VALUES (@MATD_DA, @MAMA, @TENMA, @MIEUTA, @GIA) 
    END TRY


    BEGIN CATCH
        ROLLBACK  
        RETURN 0
    END CATCH

     COMMIT TRAN  
    RETURN 1
END
