--2) LOI
DROP PROC IF EXISTS EX_2_READ_INFO_UNCOMMITTED_READ  
GO
CREATE PROC EX_2_READ_INFO_UNCOMMITTED_READ
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
    BEGIN TRAN 
    BEGIN TRY 
        SELECT * FROM NHANVIEN

    END TRY 

    BEGIN CATCH 
        ROLLBACK TRAN
        RETURN 0
    END CATCH
    COMMIT TRAN
    RETURN 1
END 

GO



DROP PROC IF EXISTS  EX_2_UPDATE_INFO_UNCOMMITTED_READ
GO 
CREATE PROC EX_2_UPDATE_INFO_UNCOMMITTED_READ
        @MANV CHAR(6),
        @TENNV nvarchar(50)
AS
BEGIN
    BEGIN TRAN
        IF NOT EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV )
        BEGIN
            ROLLBACK  
            RETURN 0
        END
        UPDATE NHANVIEN SET TENNV = @TENNV WHERE MANV = @MANV 
        SELECT *  FROM NHANVIEN    
        WAITFOR DELAY '00:00:05'  
    ROLLBACK TRAN
    RETURN 1
END